version: '3'
services:
  config-service:
    image: config-service
    ports:
     - "8888:8888"
  eureka-services:
    image: eureka-services
    ports:
     - "8761:8761"
    depends_on:
     - config-service
  hystrix-dashboard:
    image: hystrix-dashboard
    ports:
     - "8010:8010"
    depends_on:
     - eureka-services
  zipkin-service:
    image: zipkin-service
    ports:
     - "9411:9411"
    depends_on:
     - eureka-services
  reservation-services:
    image: reservation-services
    ports:
     - "8000:8000"
    depends_on:
     - config-service
  reservation-client:
    image: reservation-client
    ports:
     - "8080:8080"
    depends_on:
     - config-service